version: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      # - image: python:2.7.12
      # - image: node:5.10.1
      - image: docker:17.11.0-ce-git
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: Installation of build dependencies.
          command: |
            apk add --no-cache bash curl     
            curl -sSL https://s3.amazonaws.com/circle-downloads/install-circle-env.sh | bash
      - run:
          name: testing tag
          command: |
            echo "dev job"
            echo "python test"
            cat /etc/*-release
            echo $var1
            /bin/bash abc.sh
      - run:
          name: testing eee tag
          command: |
            echo $var1
            echo $var2
            echo $var3
            echo $var4c
            echo $var5c           
      - run:
          name: testing e232ee tag
          command: |
            echo $var1
            echo $var2
            echo $var3  
            echo $var4c
            echo $var5c              
      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "dev deploy"

  "build-dev-core":
    docker:
      - image: python:2.7.12
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: testing tag
          command: |
            echo "dev core job"
            echo "python test"

      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "dev core deploy"
          
  # Build & Deploy against production backend
  "build-prod":
    docker:
      - image: python:2.7.12
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: testing tag
          command: |
            echo "prod job"
            echo "python test"

      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "prod deploy"

  "build-prod-core":
    docker:
      - image: python:2.7.12
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: testing tag
          command: |
            echo "prod core job"
            echo "python test"

      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "prod core deploy"

  # Build & Deploy against QA backend
  "build-qa":
    docker:
      - image: python:2.7.12
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: testing tag
          command: |
            echo "qa job"
            echo "python test"

      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "qa deploy"
  "build-qa-core":
    docker:
      - image: python:2.7.12
    steps:
      # Initialization.
      - checkout
      # Build of Docker image.
      - run:
          name: testing tag
          command: |
            echo "qa core job"
            echo "python test"

      # Deployment.
      - deploy:
          command: |
            python nosetest.py
            echo "qa core deploy"
          
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: dev-var
